version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "pg"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust