"""initial

Revision ID: c05d6ae67c65
Revises: 
Create Date: 2023-02-05 15:54:03.148720

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c05d6ae67c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computers',
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('visited_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cpu_hhz', sa.Float(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('ssd_gb', sa.Integer(), nullable=True),
    sa.Column('price_rub', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computers')
    # ### end Alembic commands ###
